// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEQjMP-j5f4oCxjMXzGrPOykgr0xMhamI',
    appId: '1:374852436729:web:c64e0157ecd01987dcd828',
    messagingSenderId: '374852436729',
    projectId: 'bookedex-cd74a',
    authDomain: 'bookedex-cd74a.firebaseapp.com',
    storageBucket: 'bookedex-cd74a.firebasestorage.app',
    measurementId: 'G-0KTJF5C7TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Qw5D3KUU4gcWapXPILX12Q61bgfmsqE',
    appId: '1:374852436729:android:ac8df8728bec3e35dcd828',
    messagingSenderId: '374852436729',
    projectId: 'bookedex-cd74a',
    storageBucket: 'bookedex-cd74a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_wf8Q-nnVeb70IW9lIrGIrWiY5SvdL5w',
    appId: '1:374852436729:ios:2a5987940394dcdfdcd828',
    messagingSenderId: '374852436729',
    projectId: 'bookedex-cd74a',
    storageBucket: 'bookedex-cd74a.firebasestorage.app',
    iosClientId: '374852436729-92dklve46ihl365dfb7qh3b3f9rulotn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshelfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_wf8Q-nnVeb70IW9lIrGIrWiY5SvdL5w',
    appId: '1:374852436729:ios:2a5987940394dcdfdcd828',
    messagingSenderId: '374852436729',
    projectId: 'bookedex-cd74a',
    storageBucket: 'bookedex-cd74a.firebasestorage.app',
    iosClientId: '374852436729-92dklve46ihl365dfb7qh3b3f9rulotn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshelfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEQjMP-j5f4oCxjMXzGrPOykgr0xMhamI',
    appId: '1:374852436729:web:4eb7f1484c26a7eedcd828',
    messagingSenderId: '374852436729',
    projectId: 'bookedex-cd74a',
    authDomain: 'bookedex-cd74a.firebaseapp.com',
    storageBucket: 'bookedex-cd74a.firebasestorage.app',
    measurementId: 'G-DQ98VGYYN8',
  );
}
